const std = @import("std");
const zcc = @import("compile_commands");

/// Warning flags for the C this project owns. -Wall and -Wextra are the baseline; -Wconversion
/// earns its place beside them because the wire and mapping code narrows constantly -- a size_t
/// string length into a uint8_t field, an int count from pbtools into a uint8_t, a uint64_t into
/// a uint32_t. A silent narrowing there is how a truncated value reaches a consumer instead of
/// an error, so every remaining one is meant to carry an explicit cast next to the check that
/// bounds it. Mirrors the flags arnm holds itself to and what CMakeLists.txt sets.
///
/// zig hides C warnings on a successful build and turns them into errors on a failing one, so
/// the CMake build is where these actually get read. They are set here so the two builds
/// compile the same language and neither can drift into accepting what the other rejects.
const c_flags = [_][]const u8{ "-Wall", "-Wextra", "-Wconversion" };

/// What the two source sets this project does not get to keep clean are compiled with:
///   third_party/  is vendored -- not ours to change
///   data/proto/   is generated by update_proto.sh, which deletes and rewrites the folders, so
///                 a fix there survives exactly until the next run
/// Same two exclusions lint.sh has.
const c_flags_foreign = [_][]const u8{};

/// Recursively add .c files from a directory
fn addDirSources(
    lib: *std.Build.Step.Compile,
    b: *std.Build,
    dir_path: []const u8,
    flags: []const []const u8,
) void {
    var dir = b.build_root.handle.openDir(dir_path, .{ .iterate = true }) catch |err| {
        std.debug.panic("Failed to open directory '{s}': {s}", .{ dir_path, @errorName(err) });
    };
    defer dir.close();

    var walker = dir.walk(b.allocator) catch |err| {
        std.debug.panic("Failed to walk directory '{s}': {s}", .{ dir_path, @errorName(err) });
    };
    defer walker.deinit();

    while (walker.next() catch null) |entry| {
        if (entry.kind == .file and std.mem.endsWith(u8, entry.path, ".c")) {
            const full_path = b.fmt("{s}/{s}", .{ dir_path, entry.path });
            // the generated pbtools output sits under src/, so it is sorted out here rather
            // than by the directory the walk was started on
            const generated = std.mem.indexOf(u8, full_path, "/data/proto/") != null;
            lib.addCSourceFiles(.{
                .files = &[_][]const u8{full_path},
                .flags = if (generated) &c_flags_foreign else flags,
            });
        }
    }
}

/// Sanitizers the zig toolchain can apply to the C/C++ sources of this project.
///
/// AddressSanitizer is deliberately absent: zig does not ship the asan runtime, so
/// `-fsanitize=address` would compile but fail to link. Use the CMake build with
/// `-DENABLE_SANITIZERS=ON` for a leak and out-of-bounds check.
const SanitizeMode = enum {
    /// no instrumentation
    off,
    /// UndefinedBehaviorSanitizer, aborting with a diagnostic on the first finding
    undefined_behavior,
    /// ThreadSanitizer, reporting data races between threads
    thread,
};

/// Instrument a module according to @p mode. Applied to every target of the build so that
/// library and test binary always agree on their instrumentation.
fn applySanitize(module: *std.Build.Module, mode: SanitizeMode) void {
    switch (mode) {
        .off => {},
        .undefined_behavior => module.sanitize_c = .full,
        .thread => module.sanitize_thread = true,
    }
}

const BuildContext = struct {
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    core_lib: *std.Build.Step.Compile,
    arnm_dep: *std.Build.Dependency,
    googletest_dep: ?*std.Build.Dependency,
    sodium_dep: ?*std.Build.Dependency,
    singleOutputDir: bool,
    sanitize: SanitizeMode,
    cdb: *std.ArrayList(*std.Build.Step.Compile),
};

const BuildTarget = struct {
    link_googletest: bool = false,
    link_sodium: bool = false,
    name: []const u8,
    srcs: []const []const u8,
};

fn processBuildTarget(context: *const BuildContext, build_target: BuildTarget, path: []const u8) void {
    const b = context.b;
    const exe = b.addExecutable(.{
        .name = build_target.name,
        .root_module = b.createModule(.{
            .target = context.target,
            .optimize = context.optimize,
        }),
    });

    applySanitize(exe.root_module, context.sanitize);
    exe.linkLibrary(context.core_lib);

    if (build_target.link_googletest) {
        if (context.googletest_dep) |dep| {
            exe.linkLibrary(dep.artifact("gtest"));
            exe.linkLibrary(dep.artifact("gtest_main"));
        }
    }
    if (build_target.link_sodium) {
        exe.root_module.addCMacro("USE_SODIUM", "1");
        if (context.sodium_dep) |dep| {
            exe.linkLibrary(dep.artifact(if (context.target.result.os.tag == .windows) "libsodium-static" else "sodium"));
        }
    }

    exe.addIncludePath(b.path("include"));
    exe.addSystemIncludePath(b.path("third_party"));
    exe.addIncludePath(context.arnm_dep.path("include"));

    for (build_target.srcs) |src_file| {
        exe.addCSourceFiles(.{
            .files = &.{b.fmt("{s}/{s}", .{ path, src_file })},
            // the googletest translation units stay exempt: they are C++ over a framework this
            // project does not own, and -Wconversion there reports gtest's macros, not our code
            .flags = if (std.mem.endsWith(u8, src_file, ".c")) &c_flags else &c_flags_foreign,
        });
    }

    context.cdb.append(b.allocator, exe) catch @panic("OOM");

    if (context.singleOutputDir) {
        const bin_install_step = b.addInstallBinFile(exe.getEmittedBin(), b.fmt("../{s}", .{exe.out_filename}));
        b.getInstallStep().dependOn(&bin_install_step.step);
    } else {
        b.installArtifact(exe);
    }
}

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    // make a list of targets that have include files and c source files
    var cdbTargets: std.ArrayList(*std.Build.Step.Compile) = .empty;

    // Options
    const enable_benchmarks = b.option(bool, "benchmarks", "Enable benchmarks") orelse false;
    const enable_tests = b.option(bool, "tests", "Enable tests") orelse false;
    const enable_sodium = b.option(bool, "sodium", "Enable sodium and crypto") orelse false;
    const lib_shared = b.option(bool, "shared", "Make lib shared") orelse false;
    const singleOutputDir = b.option(bool, "singleOutputDir", "Put direct into output folder, without lib or bin folder") orelse false;
    const sanitize = b.option(SanitizeMode, "sanitize", "Instrument C sources: undefined_behavior (UBSan) or thread (TSan). AddressSanitizer needs the CMake build with -DENABLE_SANITIZERS=ON") orelse .off;

    const core_lib = b.addLibrary(.{ .name = "gradido_blockchain_core", .linkage = if (lib_shared) .dynamic else .static, .root_module = b.createModule(.{
        .target = target,
        .optimize = optimize,
    }) });
    applySanitize(core_lib.root_module, sanitize);

    // arnm carries the allocator, the containers and the conversions this project used to
    // keep in src/utils. It was called hostmem until arnm 0.5.0, which renamed every symbol.
    // It is pulled in as a package, not vendored.
    const arnm_dep = b.dependency("arnm", .{ .target = target, .optimize = optimize });

    const context: BuildContext = .{
        .b = b,
        .target = target,
        .optimize = optimize,
        .core_lib = core_lib,
        .arnm_dep = arnm_dep,
        .googletest_dep = b.lazyDependency("googletest", .{
            .target = target,
            .optimize = optimize,
        }),
        .sodium_dep = b.lazyDependency("libsodium", .{
            .target = target,
            .optimize = optimize,
            .static = true,
            .shared = false,
        }),
        .singleOutputDir = singleOutputDir,
        .sanitize = sanitize,
        .cdb = &cdbTargets,
    };

    if (enable_sodium) {
        core_lib.root_module.addCMacro("USE_SODIUM", "1");
        if (context.sodium_dep) |dep| {
            core_lib.linkLibrary(dep.artifact(if (target.result.os.tag == .windows) "libsodium-static" else "sodium"));
        }
    }

    core_lib.linkLibC();
    core_lib.linkLibrary(arnm_dep.artifact("arnm"));
    core_lib.addIncludePath(arnm_dep.path("include"));

    core_lib.addIncludePath(b.path("include"));
    core_lib.addIncludePath(b.path("include/gradido_blockchain_core/data/proto/gradido"));
    // system paths: a vendored header is not ours to keep clean under c_flags, and r128.h does
    // its arithmetic inline -- compiling third_party/*.c without the flags is not enough when
    // the warning comes from a header one of our own translation units included. Mirrors the
    // include_directories(SYSTEM ...) block in CMakeLists.txt.
    core_lib.addSystemIncludePath(b.path("third_party"));
    core_lib.addSystemIncludePath(b.path("third_party/pbtools"));

    addDirSources(core_lib, b, "src", &c_flags);
    addDirSources(core_lib, b, "third_party", &c_flags_foreign);

    // keep track of it, so later we can pass it to compile_commands
    cdbTargets.append(b.allocator, core_lib) catch @panic("OOM");

    if (singleOutputDir) {
        const bin_install_step = b.addInstallBinFile(core_lib.getEmittedBin(), b.fmt("../{s}", .{core_lib.out_filename}));
        b.getInstallStep().dependOn(&bin_install_step.step);
        if (target.result.os.tag == .windows) {
            const lib_install_step = b.addInstallLibFile(core_lib.getEmittedImplib(), b.fmt("../{s}", .{core_lib.out_lib_filename}));
            b.getInstallStep().dependOn(&lib_install_step.step);
        }
    } else {
        b.installArtifact(core_lib);
    }
    if (enable_benchmarks) {
      const path = "benchmarks/src";
      processBuildTarget(&context, .{
          .link_googletest = false,
          .link_sodium = enable_sodium,
          .name = "bench_numberToString",
          .srcs = &.{"bench_numberToString.c"},
      }, path);
      // The JSON benchmark builds its fixtures rather than decoding a sample, so it needs no
      // libsodium and runs in every build.
      processBuildTarget(&context, .{ .link_googletest = false, .link_sodium = enable_sodium, .name = "bench_json", .srcs = &.{"bench_json.c"} }, path);
      if (enable_sodium) {
        processBuildTarget(&context, .{ .link_googletest = false, .link_sodium = true, .name = "bench_crypto", .srcs = &.{"bench_crypto.c"} }, path);
        // Puts arnm's base64 -- the pair the JSON mapping uses -- next to libsodium's, so
        // needs sodium even though nothing of the mapping does.
        processBuildTarget(&context, .{ .link_googletest = false, .link_sodium = true, .name = "bench_base64", .srcs = &.{"bench_base64.c"} }, path);
      }
    }

    if (enable_tests) {
        const path = "tests/unit/src";
        processBuildTarget(&context, .{ .link_googletest = true, .link_sodium = false, .name = "data", .srcs = &.{"test_data.cpp"} }, path);
        processBuildTarget(&context, .{ .link_googletest = true, .link_sodium = false, .name = "data_wire", .srcs = &.{"test_data_wire.cpp"} }, path);
        processBuildTarget(&context, .{ .link_googletest = true, .link_sodium = false, .name = "test_unit", .srcs = &.{"test_unit.cpp"} }, path);
        processBuildTarget(&context, .{ .link_googletest = true, .link_sodium = false, .name = "test_json", .srcs = &.{"test_json.cpp"} }, path);
        if (enable_sodium) {
            processBuildTarget(&context, .{ .link_googletest = true, .link_sodium = true, .name = "test_converter", .srcs = &.{"test_converter.cpp"} }, path);
            processBuildTarget(&context, .{ .link_googletest = true, .link_sodium = true, .name = "test_crypto", .srcs = &.{ "test_crypto.cpp", "utils.cpp" } }, path);
            processBuildTarget(&context, .{ .link_googletest = true, .link_sodium = true, .name = "test_pbtools", .srcs = &.{ "test_pbtools.cpp", "key_pairs.cpp" } }, path);
            processBuildTarget(&context, .{ .link_googletest = true, .link_sodium = true, .name = "test_runtime", .srcs = &.{ "test_runtime.cpp", "key_pairs.cpp" } }, path);
        }
    }

    const cdbTargetsSlice = cdbTargets.toOwnedSlice(b.allocator) catch @panic("OOM");
    const buildStep = zcc.createStep(b, "cdb", cdbTargetsSlice);
    // Build everything in the project before generating the compile_commands
    for (cdbTargetsSlice) |cdbTarget| buildStep.dependOn(&cdbTarget.step);
}
