#!/bin/bash
# Formats every source file the project owns.
#
# find, not a ladder of */**/ globs: bash expands ** like a single * unless globstar is set,
# so such a ladder reaches a fixed depth and quietly stops there. src/data/proto/gradido sat
# one level below the deepest rung and was never formatted.
set -uo pipefail
cd "$(dirname "$0")"

# Two trees stay out on purpose:
#   third_party/  is vendored — not ours to reformat
#   */data/proto/ is generated by update_proto.sh (pbtools), which deletes and rewrites the
#                 folders; formatting them only produces a diff the next run discards
find src include tests/unit/src benchmarks/src \
  \( -name "*.c" -o -name "*.h" -o -name "*.cpp" \) \
  -not -path "*/data/proto/*" \
  -print0 | xargs -0 clang-format -i

count=$(find src include tests/unit/src benchmarks/src \
  \( -name "*.c" -o -name "*.h" -o -name "*.cpp" \) \
  -not -path "*/data/proto/*" | wc -l)
echo "formatted $count files"
