#include "gradido_blockchain_core/types/address.h"
#include "gradido_blockchain_core/utils/string_helper.h"

#include <stdint.h>
#include <string.h>

#define GRDT_ADDRESS_NONE_STRING "GRDT_ADDRESS_NONE"
#define GRDT_ADDRESS_COMMUNITY_HUMAN_STRING "GRDT_ADDRESS_COMMUNITY_HUMAN"
#define GRDT_ADDRESS_COMMUNITY_GMW_STRING "GRDT_ADDRESS_COMMUNITY_GMW"
#define GRDT_ADDRESS_COMMUNITY_AUF_STRING "GRDT_ADDRESS_COMMUNITY_AUF"
#define GRDT_ADDRESS_COMMUNITY_PROJECT_STRING "GRDT_ADDRESS_COMMUNITY_PROJECT"
#define GRDT_ADDRESS_SUBACCOUNT_STRING "GRDT_ADDRESS_SUBACCOUNT"
#define GRDT_ADDRESS_CRYPTO_ACCOUNT_STRING "GRDT_ADDRESS_CRYPTO_ACCOUNT"
#define GRDT_ADDRESS_DEFERRED_TRANSFER_STRING "GRDT_ADDRESS_DEFERRED_TRANSFER"

static const char *messages[] = {
    [GRDT_ADDRESS_NONE] = GRDT_ADDRESS_NONE_STRING,
    [GRDT_ADDRESS_COMMUNITY_HUMAN] = GRDT_ADDRESS_COMMUNITY_HUMAN_STRING,
    [GRDT_ADDRESS_COMMUNITY_GMW] = GRDT_ADDRESS_COMMUNITY_GMW_STRING,
    [GRDT_ADDRESS_COMMUNITY_AUF] = GRDT_ADDRESS_COMMUNITY_AUF_STRING,
    [GRDT_ADDRESS_COMMUNITY_PROJECT] = GRDT_ADDRESS_COMMUNITY_PROJECT_STRING,
    [GRDT_ADDRESS_SUBACCOUNT] = GRDT_ADDRESS_SUBACCOUNT_STRING,
    [GRDT_ADDRESS_CRYPTO_ACCOUNT] = GRDT_ADDRESS_CRYPTO_ACCOUNT_STRING,
    [GRDT_ADDRESS_DEFERRED_TRANSFER] = GRDT_ADDRESS_DEFERRED_TRANSFER_STRING
};
const char *grdt_address_to_string(grdt_address address) {
  if (address < 0 || address >= (int)(sizeof(messages) / sizeof(messages[0]))) {
    return "GRDT_ADDRESS_UNKNOWN";
  }

  const char *msg = messages[address];
  return msg ? msg : "GRDT_ADDRESS_UNKNOWN";
}

grdt_address grdt_address_from_string(const char *address_string, size_t string_size) {
  if (GRDU_STRING_EQUALS(address_string, string_size, GRDT_ADDRESS_COMMUNITY_HUMAN_STRING)) {
    return GRDT_ADDRESS_COMMUNITY_HUMAN;
  } else if (
      GRDU_STRING_EQUALS(address_string, string_size, GRDT_ADDRESS_DEFERRED_TRANSFER_STRING)) {
    return GRDT_ADDRESS_DEFERRED_TRANSFER;
  } else if (GRDU_STRING_EQUALS(address_string, string_size, GRDT_ADDRESS_COMMUNITY_GMW_STRING)) {
    return GRDT_ADDRESS_COMMUNITY_GMW;
  } else if (GRDU_STRING_EQUALS(address_string, string_size, GRDT_ADDRESS_COMMUNITY_AUF_STRING)) {
    return GRDT_ADDRESS_COMMUNITY_AUF;
  } else if (
      GRDU_STRING_EQUALS(address_string, string_size, GRDT_ADDRESS_COMMUNITY_PROJECT_STRING)) {
    return GRDT_ADDRESS_COMMUNITY_PROJECT;
  } else if (GRDU_STRING_EQUALS(address_string, string_size, GRDT_ADDRESS_SUBACCOUNT_STRING)) {
    return GRDT_ADDRESS_SUBACCOUNT;
  } else if (GRDU_STRING_EQUALS(address_string, string_size, GRDT_ADDRESS_CRYPTO_ACCOUNT_STRING)) {
    return GRDT_ADDRESS_CRYPTO_ACCOUNT;
  }
  return GRDT_ADDRESS_NONE;
}
