#include "gradido_blockchain_core/types/ledger_anchor.h"
#include "gradido_blockchain_core/utils/string_helper.h"

#include <stdint.h>
#include <string.h>

#define GRDT_LEDGER_ANCHOR_UNSPECIFIED_STRING "GRDT_LEDGER_ANCHOR_UNSPECIFIED"
#define GRDT_LEDGER_ANCHOR_HIERO_TRANSACTION_ID_STRING "GRDT_LEDGER_ANCHOR_HIERO_TRANSACTION_ID"
#define GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_ID_STRING                                 \
  "GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_ID"
#define GRDT_LEDGER_ANCHOR_NODE_TRIGGER_TRANSACTION_ID_STRING                                      \
  "GRDT_LEDGER_ANCHOR_NODE_TRIGGER_TRANSACTION_ID"
#define GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_COMMUNITY_ID_STRING                                   \
  "GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_COMMUNITY_ID"
#define GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_USER_ID_STRING                                        \
  "GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_USER_ID"
#define GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_CONTRIBUTION_ID_STRING                                \
  "GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_CONTRIBUTION_ID"
#define GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_LINK_ID_STRING                            \
  "GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_LINK_ID"

const char *grdt_ledger_anchor_to_string(grdt_ledger_anchor ledger_anchor) {
  static const char *messages[] = {
      [GRDT_LEDGER_ANCHOR_UNSPECIFIED] = GRDT_LEDGER_ANCHOR_UNSPECIFIED_STRING,
      [GRDT_LEDGER_ANCHOR_HIERO_TRANSACTION_ID] = GRDT_LEDGER_ANCHOR_HIERO_TRANSACTION_ID_STRING,
      [GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_ID] =
          GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_ID_STRING,
      [GRDT_LEDGER_ANCHOR_NODE_TRIGGER_TRANSACTION_ID] =
          GRDT_LEDGER_ANCHOR_NODE_TRIGGER_TRANSACTION_ID_STRING,
      [GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_COMMUNITY_ID] =
          GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_COMMUNITY_ID_STRING,
      [GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_USER_ID] =
          GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_USER_ID_STRING,
      [GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_CONTRIBUTION_ID] =
          GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_CONTRIBUTION_ID_STRING,
      [GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_LINK_ID] =
          GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_LINK_ID_STRING,
  };

  if (ledger_anchor < 0 || ledger_anchor >= (int)(sizeof(messages) / sizeof(messages[0]))) {
    return "GRDT_LEDGER_ANCHOR_UNKNOWN";
  }

  const char *msg = messages[ledger_anchor];
  return msg ? msg : "GRDT_LEDGER_ANCHOR_UNKNOWN";
}

grdt_ledger_anchor grdt_ledger_anchor_from_string(
    const char *ledger_anchor_string, size_t string_size
) {
  if (GRDU_STRING_EQUALS(
          ledger_anchor_string, string_size, GRDT_LEDGER_ANCHOR_HIERO_TRANSACTION_ID_STRING
      )) {
    return GRDT_LEDGER_ANCHOR_HIERO_TRANSACTION_ID;
  } else if (
      GRDU_STRING_EQUALS(
          ledger_anchor_string, string_size,
          GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_ID_STRING
      )) {
    return GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_ID;
  } else if (
      GRDU_STRING_EQUALS(
          ledger_anchor_string, string_size, GRDT_LEDGER_ANCHOR_NODE_TRIGGER_TRANSACTION_ID_STRING
      )) {
    return GRDT_LEDGER_ANCHOR_NODE_TRIGGER_TRANSACTION_ID;
  } else if (
      GRDU_STRING_EQUALS(
          ledger_anchor_string, string_size,
          GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_LINK_ID_STRING
      )) {
    return GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_LINK_ID;
  } else if (
      GRDU_STRING_EQUALS(
          ledger_anchor_string, string_size,
          GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_CONTRIBUTION_ID_STRING
      )) {
    return GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_CONTRIBUTION_ID;
  } else if (
      GRDU_STRING_EQUALS(
          ledger_anchor_string, string_size, GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_USER_ID_STRING
      )) {
    return GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_USER_ID;
  } else if (
      GRDU_STRING_EQUALS(
          ledger_anchor_string, string_size,
          GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_COMMUNITY_ID_STRING
      )) {
    return GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_COMMUNITY_ID;
  }
  return GRDT_LEDGER_ANCHOR_UNSPECIFIED;
}
