#include "gradido_blockchain_core/types/transaction.h"
#include "gradido_blockchain_core/utils/string_helper.h"

#include <stdint.h>
#include <string.h>

#define GRDT_TRANSACTION_NONE_STRING "GRDT_TRANSACTION_NONE"
#define GRDT_TRANSACTION_CREATION_STRING "GRDT_TRANSACTION_CREATION"
#define GRDT_TRANSACTION_TRANSFER_STRING "GRDT_TRANSACTION_TRANSFER"
#define GRDT_TRANSACTION_COMMUNITY_FRIENDS_UPDATE_STRING "GRDT_TRANSACTION_COMMUNITY_FRIENDS_UPDATE"
#define GRDT_TRANSACTION_REGISTER_ADDRESS_STRING "GRDT_TRANSACTION_REGISTER_ADDRESS"
#define GRDT_TRANSACTION_DEFERRED_TRANSFER_STRING "GRDT_TRANSACTION_DEFERRED_TRANSFER"
#define GRDT_TRANSACTION_COMMUNITY_ROOT_STRING "GRDT_TRANSACTION_COMMUNITY_ROOT"
#define GRDT_TRANSACTION_REDEEM_DEFERRED_TRANSFER_STRING "GRDT_TRANSACTION_REDEEM_DEFERRED_TRANSFER"
#define GRDT_TRANSACTION_TIMEOUT_DEFERRED_TRANSFER_STRING                                          \
  "GRDT_TRANSACTION_TIMEOUT_DEFERRED_TRANSFER"

const char *grdt_transaction_to_string(grdt_transaction transaction) {
  static const char *messages[] = {
      [GRDT_TRANSACTION_NONE] = GRDT_TRANSACTION_NONE_STRING,
      [GRDT_TRANSACTION_CREATION] = GRDT_TRANSACTION_CREATION_STRING,
      [GRDT_TRANSACTION_TRANSFER] = GRDT_TRANSACTION_TRANSFER_STRING,
      [GRDT_TRANSACTION_COMMUNITY_FRIENDS_UPDATE] =
          GRDT_TRANSACTION_COMMUNITY_FRIENDS_UPDATE_STRING,
      [GRDT_TRANSACTION_REGISTER_ADDRESS] = GRDT_TRANSACTION_REGISTER_ADDRESS_STRING,
      [GRDT_TRANSACTION_DEFERRED_TRANSFER] = GRDT_TRANSACTION_DEFERRED_TRANSFER_STRING,
      [GRDT_TRANSACTION_COMMUNITY_ROOT] = GRDT_TRANSACTION_COMMUNITY_ROOT_STRING,
      [GRDT_TRANSACTION_REDEEM_DEFERRED_TRANSFER] =
          GRDT_TRANSACTION_REDEEM_DEFERRED_TRANSFER_STRING,
      [GRDT_TRANSACTION_TIMEOUT_DEFERRED_TRANSFER] =
          GRDT_TRANSACTION_TIMEOUT_DEFERRED_TRANSFER_STRING,
  };

  if (transaction < 0 || transaction >= (int)(sizeof(messages) / sizeof(messages[0]))) {
    return "GRDT_TRANSACTION_UNKNOWN";
  }

  const char *msg = messages[transaction];
  return msg ? msg : "GRDT_TRANSACTION_UNKNOWN";
}

grdt_transaction grdt_transaction_from_string(const char *transaction_string, size_t string_size) {
  if (GRDU_STRING_EQUALS(transaction_string, string_size, GRDT_TRANSACTION_TRANSFER_STRING)) {
    return GRDT_TRANSACTION_TRANSFER;
  } else if (
      GRDU_STRING_EQUALS(transaction_string, string_size, GRDT_TRANSACTION_CREATION_STRING)) {
    return GRDT_TRANSACTION_CREATION;
  } else if (
      GRDU_STRING_EQUALS(
          transaction_string, string_size, GRDT_TRANSACTION_REGISTER_ADDRESS_STRING
      )) {
    return GRDT_TRANSACTION_REGISTER_ADDRESS;
  } else if (
      GRDU_STRING_EQUALS(
          transaction_string, string_size, GRDT_TRANSACTION_DEFERRED_TRANSFER_STRING
      )) {
    return GRDT_TRANSACTION_DEFERRED_TRANSFER;
  } else if (
      GRDU_STRING_EQUALS(
          transaction_string, string_size, GRDT_TRANSACTION_REDEEM_DEFERRED_TRANSFER_STRING
      )) {
    return GRDT_TRANSACTION_REDEEM_DEFERRED_TRANSFER;
  } else if (
      GRDU_STRING_EQUALS(
          transaction_string, string_size, GRDT_TRANSACTION_TIMEOUT_DEFERRED_TRANSFER_STRING
      )) {
    return GRDT_TRANSACTION_TIMEOUT_DEFERRED_TRANSFER;
  } else if (
      GRDU_STRING_EQUALS(transaction_string, string_size, GRDT_TRANSACTION_COMMUNITY_ROOT_STRING)) {
    return GRDT_TRANSACTION_COMMUNITY_ROOT;
  } else if (
      GRDU_STRING_EQUALS(
          transaction_string, string_size, GRDT_TRANSACTION_COMMUNITY_FRIENDS_UPDATE_STRING
      )) {
    return GRDT_TRANSACTION_COMMUNITY_FRIENDS_UPDATE;
  }
  return GRDT_TRANSACTION_NONE;
}
