#ifndef GRADIDO_BLOCKCHAIN_CORE_UTILS_BUCKET_VECTOR_H
#define GRADIDO_BLOCKCHAIN_CORE_UTILS_BUCKET_VECTOR_H

#include "gradido_blockchain_core/memory.h"
#include "gradido_blockchain_core/result.h"

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @defgroup utils Utilities */

/**
 * @defgroup grdu_bucket_vector grdu_bucket_vector
 * @ingroup utils
 * @brief Growing sequence of fixed-size buckets — a deque without push_front.
 *
 * Elements settle into buckets of `1 << log2_bucket` slots. A bucket, once allocated, never
 * moves: growth appends a new one and only the small index array of bucket pointers is
 * reallocated. Two properties follow from that stillness:
 *
 * - **Pointer stability**: pointers from `_at`, `_get`, `_back`, `_emplace` stay valid until
 *   the element is popped or the vector is freed or cleared. A contiguous array cannot
 *   promise this.
 * - **No copy on growth**: appending never moves existing payload, so `_push` latency stays
 *   flat instead of spiking with the element count.
 *
 * Random access costs a shift, a mask and one extra load: `buckets[i >> shift][i & mask]`.
 * Iterating bucket by bucket runs over contiguous memory and is the fastest traversal.
 *
 * Complexity: `_push` / `_emplace` / `_pop` amortized O(1) (one compare on the fast path),
 * `_at` / `_get` O(1), `_clear` O(1), `_shrink` / `_free` O(bucket count).
 *
 * ### Memory that comes back
 *
 * Growth is one-directional on its own: `_pop` leaves the vacated bucket in place and
 * `_clear` keeps all of them, so the next push finds its storage ready. A vector sits at its
 * high water mark until `_shrink` says otherwise — it releases the buckets past the last
 * element and tightens the index array onto the rest, without moving a live element. Call it
 * where a peak is behind you, not between pushes.
 *
 * @note Under an arena `_shrink` gives back what the arena will take: it unwinds from the
 * last bucket and stops at the first that is not the arena's most recent allocation, since
 * only that one can move the bump index. Buckets sitting before a superseded index array
 * therefore stay until the arena's own reset. GRD_SUCCESS either way — a partial reclaim
 * strands nothing that was not already stranded.
 *
 * ### Empty states
 *
 * A vector is empty after `_init`, `_clear`, `_free` — and when zero-initialized: `name v =
 * {0};` is valid and usable, with the malloc/free allocator. Every read path answers for it
 * (`_size` 0, `_at` / `_front` / `_back` NULL, `_bucket_count` 0, `_pop` out of bounds) and
 * the first `_push` opens the first bucket. Prefer `_init` when an allocator is involved: it
 * is the only way to attach one.
 *
 * ### Ownership of the payload
 *
 * The container owns its buckets, never what they hold. Pointers in the payload are the
 * caller's to manage.
 *
 * @code
 * // removing one element: hand back what it owns, then drop the slot
 * grdu_memory_block_free(&tx_vec_back(&v)->signature, alloc);
 * tx_vec_pop(&v);
 *
 * // removing all of them: the same duty, once per element
 * grdw_gradido_transaction *tx;
 * GRDU_BVEC_FOREACH(tx_vec, &v, tx, i) { grdu_memory_block_free(&tx->signature, alloc); }
 * tx_vec_free(&v);
 * @endcode
 *
 * Payloads of plain data — integers, hashes, fixed-size structs, or pointers into an arena
 * that outlives the vector — need none of this and are what the container is built for.
 *
 * @warning `_clear` and `_free` discard every element at once, `_pop` the last one. Release
 * what the payloads own first; afterwards the slots are unreachable and the ownership with
 * them.
 *
 * ### Instantiation
 *
 * Generated by macro, once per payload type:
 *
 * @code
 * // header-only, all functions static inline
 * GRDU_BVEC_STATIC(tx_vec, grdw_gradido_transaction, 7)  // 128 elements per bucket
 *
 * tx_vec v;
 * tx_vec_init(&v, NULL);                 // NULL => malloc/free
 * grdw_gradido_transaction *slot;
 * if (tx_vec_emplace(&v, &slot) == GRD_SUCCESS) {
 *   // fill *slot in place, no copy
 * }
 * tx_vec_free(&v);
 *
 * // shared across translation units, split the generation:
 * GRDU_BVEC_DECLARE(tx_vec, grdw_gradido_transaction, 7, extern)  // header
 * GRDU_BVEC_DEFINE(tx_vec, grdw_gradido_transaction, 7,)          // exactly one .c file
 * @endcode
 *
 * @note Choose `log2_bucket` so one bucket spans a few cache lines up to a page:
 * `sizeof(type) << log2_bucket` between 512 B and 64 KiB is a sound default. Small buckets
 * pay more index lookups, large ones waste tail space.
 *
 * @note Arena memory is 8-byte aligned; payloads needing stricter alignment want NULL
 * (malloc/free) or an externally aligned arena. An arena cannot reclaim a superseded index
 * array, so `_reserve` up front is worth it there.
 *
 * @note The hot-path functions (`_push`, `_emplace`, `_pop`, `_get`, `_at`, `_back`,
 * `_front`, `_size`) do not validate their vector pointer. Passing NULL is a programming
 * error, not a runtime condition.
 *
 * @whisper Each bucket fills, then rests — the sequence grows without disturbing what settled
 *
 * @{
 */

/** @brief Initial number of bucket pointer slots in the index array. */
#define GRDU_BVEC_INDEX_INITIAL_CAPACITY 8

/**
 * @brief Allocate a raw block through an optional allocator.
 *
 * Internal primitive of the generated containers.
 *
 * @param[in]     size      Bytes to allocate; must be > 0 and fit uint32_t.
 * @param[in,out] allocator Allocator to draw from, or NULL for malloc.
 * @return Pointer to the block, or NULL if the request could not be served.
 */
void *grdu_bvec_raw_alloc(size_t size, grd_memory *allocator);

/**
 * @brief Report whether this allocator frees blocks individually.
 *
 * True for NULL (malloc/free) and @ref GRD_MEMORY_ALLOC_TYPE_DEFAULT, false for the arena
 * modes, which can only give back their most recent allocation.
 *
 * @param[in] allocator Allocator to inspect, or NULL for malloc/free.
 * @return 1 if every free reclaims, 0 if the allocator releases collectively.
 */
int grdu_bvec_allocator_reclaims(const grd_memory *allocator);

/**
 * @brief Release a block obtained from grdu_bvec_raw_alloc().
 *
 * An arena only takes back its most recent allocation; anything before it stays until reset.
 * The return value says which happened, which is what `_shrink` stops on.
 *
 * @param[in]     ptr       Block to release; may be NULL.
 * @param[in]     size      Bytes @p ptr was allocated with. An arena needs it to recognize
 *                          its tail; ignored for malloc/free.
 * @param[in,out] allocator Allocator the block came from, or NULL for free().
 * @return true when the block really came back, false when an arena kept it.
 */
bool grdu_bvec_raw_free(void *ptr, size_t size, grd_memory *allocator);

/**
 * @brief Resize the index array of bucket pointers.
 *
 * With @p allocator NULL this is a realloc and usually stays in place. Growth passes a
 * capacity above the used count, `_shrink` passes exactly the live count to tighten the
 * array; either way the live pointers carry over, so no bucket is ever dropped.
 *
 * @param[in,out] index        Address of the index array; @c *index may be NULL on first
 *                             growth and is replaced when the block moves.
 * @param[in]     old_capacity Slots @c *index was allocated with — the allocated count, not
 *                             the used one. An arena resizes by size, so a wrong value moves
 *                             its bump index by the wrong amount.
 * @param[in]     new_capacity Requested slot count; must be > 0. Counts whose byte size
 *                             would overflow are rejected before allocating.
 * @param[in,out] allocator    Allocator to draw from, or NULL for realloc.
 * @return true on success, false on overflow or exhaustion — @c *index stays valid then.
 */
bool grdu_bvec_index_grow(
    void ***index, size_t old_capacity, size_t new_capacity, grd_memory *allocator
);

/**
 * @brief Generate the container type and the function prototypes.
 *
 * @param name         Identifier of the generated type; every function is prefixed with it.
 * @param type         Payload type stored by value.
 * @param log2_bucket  Binary logarithm of the bucket size in elements (0 … 24).
 * @param scope        Linkage of the generated functions, e.g. `extern` or `static inline`.
 */
#define GRDU_BVEC_DECLARE(name, type, log2_bucket, scope)                                          \
                                                                                                   \
  enum {                                                                                           \
    name##_BUCKET_SHIFT = (log2_bucket),                                                           \
    name##_BUCKET_CAPACITY = ((size_t)1 << (log2_bucket)),                                         \
    name##_BUCKET_MASK = name##_BUCKET_CAPACITY - 1                                                \
  };                                                                                               \
                                                                                                   \
  /** Bucket vector over `type`. Fields are internal; reach them through the API. */               \
  typedef struct name {                                                                            \
    type **buckets;         /**< Index array: one pointer per allocated bucket. */                 \
    size_t bucket_count;    /**< Buckets allocated (may exceed the buckets in use). */             \
    size_t bucket_capacity; /**< Pointer slots available in @c buckets. */                         \
    type *tail;             /**< Bucket currently being filled; NULL while empty. */               \
    size_t tail_index;      /**< Index of @c tail within @c buckets. */                            \
    size_t tail_used;       /**< Slots written in @c tail; equals BUCKET_CAPACITY when full. */    \
    size_t size;            /**< Total element count. */                                           \
    grd_memory *allocator;  /**< Allocator, or NULL for malloc/free. */                            \
  } name;                                                                                          \
                                                                                                   \
  scope grd_result name##_init(name *v, grd_memory *allocator);                                    \
  scope grd_result name##_reserve(name *v, size_t element_count);                                  \
  scope grd_result name##_shrink(name *v);                                                         \
  scope void name##_clear(name *v);                                                                \
  scope void name##_free(name *v);                                                                 \
  scope grd_result name##_grow(name *v, type **out_slot);                                          \
  scope grd_result name##_emplace(name *v, type **out_slot);                                       \
  scope grd_result name##_push(name *v, type value);                                               \
  scope grd_result name##_push_ptr(name *v, const type *value);                                    \
  scope grd_result name##_pop(name *v);                                                            \
  scope size_t name##_size(const name *v);                                                         \
  scope type *name##_get(const name *v, size_t index);                                             \
  scope type *name##_at(const name *v, size_t index);                                              \
  scope type *name##_front(const name *v);                                                         \
  scope type *name##_back(const name *v);                                                          \
  scope size_t name##_bucket_count(const name *v);                                                 \
  scope type *name##_bucket_data(const name *v, size_t bucket);                                    \
  scope size_t name##_bucket_size(const name *v, size_t bucket);                                   \
  scope grd_result name##_copy_to(const name *v, type *dst, size_t dst_capacity);

/**
 * @brief Generate the function bodies belonging to a GRDU_BVEC_DECLARE().
 *
 * Must be instantiated with the same @p name, @p type and @p log2_bucket as the declaration,
 * and — for non-static linkage — in exactly one translation unit.
 *
 * @param name         Identifier of the generated type.
 * @param type         Payload type stored by value.
 * @param log2_bucket  Binary logarithm of the bucket size in elements (0 … 24).
 * @param scope        Linkage of the generated functions; empty for external definitions.
 */
#define GRDU_BVEC_DEFINE(name, type, log2_bucket, scope)                                           \
                                                                                                   \
  /** Prepare an empty vector. Allocates nothing; the first push opens the first bucket. */        \
  scope grd_result name##_init(name *v, grd_memory *allocator) {                                   \
    if (!v) return GRD_ERROR_NULL_POINTER;                                                         \
    v->buckets = NULL;                                                                             \
    v->bucket_count = 0;                                                                           \
    v->bucket_capacity = 0;                                                                        \
    v->tail = NULL;                                                                                \
    v->tail_index = 0;                                                                             \
    v->tail_used = (size_t)name##_BUCKET_CAPACITY;                                                 \
    v->size = 0;                                                                                   \
    v->allocator = allocator;                                                                      \
    return GRD_SUCCESS;                                                                            \
  }                                                                                                \
                                                                                                   \
  /** Allocate buckets and index slots for @p element_count elements ahead of time. */             \
  scope grd_result name##_reserve(name *v, size_t element_count) {                                 \
    size_t needed;                                                                                 \
    if (!v) return GRD_ERROR_NULL_POINTER;                                                         \
    /* a request whose payload cannot fit an address space never reaches the allocator */          \
    if (element_count > SIZE_MAX / sizeof(type) ||                                                 \
        element_count > SIZE_MAX - (size_t)name##_BUCKET_MASK) {                                   \
      return GRD_ERROR_ARITHMETIC_OVERFLOW;                                                        \
    }                                                                                              \
    needed = (element_count + (size_t)name##_BUCKET_MASK) >> (size_t)name##_BUCKET_SHIFT;          \
    if (needed <= v->bucket_count) return GRD_SUCCESS;                                             \
    if (needed > v->bucket_capacity) {                                                             \
      if (!grdu_bvec_index_grow(                                                                   \
              (void ***)&v->buckets, v->bucket_capacity, needed, v->allocator                      \
          )) {                                                                                     \
        return GRD_ERROR_OUT_OF_MEMORY;                                                            \
      }                                                                                            \
      v->bucket_capacity = needed;                                                                 \
    }                                                                                              \
    while (v->bucket_count < needed) {                                                             \
      type *bucket = (type *)grdu_bvec_raw_alloc(                                                  \
          sizeof(type) * (size_t)name##_BUCKET_CAPACITY, v->allocator                              \
      );                                                                                           \
      if (!bucket) return GRD_ERROR_OUT_OF_MEMORY;                                                 \
      v->buckets[v->bucket_count++] = bucket;                                                      \
    }                                                                                              \
    return GRD_SUCCESS;                                                                            \
  }                                                                                                \
                                                                                                   \
  /** Release every bucket that holds no element and tighten the index array onto the rest. */     \
  scope grd_result name##_shrink(name *v) {                                                        \
    size_t used, i, bucket_size;                                                                   \
    if (!v) return GRD_ERROR_NULL_POINTER;                                                         \
                                                                                                   \
    used = v->tail ? v->tail_index + 1 : 0;                                                        \
    bucket_size = sizeof(type) * (size_t)name##_BUCKET_CAPACITY;                                   \
    /* top down, so an arena unwinds in allocation order; it stops at the first bucket it   */     \
    /* refuses to reclaim, and nothing is lost when it does — that block is simply kept.    */     \
    for (i = v->bucket_count; i > used; --i) {                                                     \
      if (!grdu_bvec_raw_free(v->buckets[i - 1], bucket_size, v->allocator)) break;                \
      v->buckets[i - 1] = NULL;                                                                    \
    }                                                                                              \
    v->bucket_count = i;                                                                           \
    if (!i) {                                                                                      \
      grdu_bvec_raw_free(v->buckets, v->bucket_capacity * sizeof(type *), v->allocator);           \
      v->buckets = NULL;                                                                           \
      v->bucket_capacity = 0;                                                                      \
      return GRD_SUCCESS;                                                                          \
    }                                                                                              \
    if (i == v->bucket_capacity) return GRD_SUCCESS;                                               \
    /* a refused tightening costs only unused pointer slots, so it is not an error */              \
    if (grdu_bvec_index_grow((void ***)&v->buckets, v->bucket_capacity, i, v->allocator)) {        \
      v->bucket_capacity = i;                                                                      \
    }                                                                                              \
    return GRD_SUCCESS;                                                                            \
  }                                                                                                \
                                                                                                   \
  /** Drop all elements, keep every allocated bucket for immediate reuse. O(1). */                 \
  scope void name##_clear(name *v) {                                                               \
    v->tail = NULL;                                                                                \
    v->tail_index = 0;                                                                             \
    v->tail_used = (size_t)name##_BUCKET_CAPACITY;                                                 \
    v->size = 0;                                                                                   \
  }                                                                                                \
                                                                                                   \
  /** Release every bucket and the index array, leaving a zeroed, reusable descriptor.   */        \
  scope void name##_free(name *v) {                                                                \
    size_t i;                                                                                      \
    if (!v) return;                                                                                \
    /* buckets backwards then the index array, the reverse of how they were taken */               \
    for (i = v->bucket_count; i > 0; --i) {                                                        \
      grdu_bvec_raw_free(                                                                          \
          v->buckets[i - 1], sizeof(type) * (size_t)name##_BUCKET_CAPACITY, v->allocator           \
      );                                                                                           \
    }                                                                                              \
    grdu_bvec_raw_free(v->buckets, v->bucket_capacity * sizeof(type *), v->allocator);             \
    v->buckets = NULL;                                                                             \
    v->bucket_count = 0;                                                                           \
    v->bucket_capacity = 0;                                                                        \
    v->tail = NULL;                                                                                \
    v->tail_index = 0;                                                                             \
    v->tail_used = (size_t)name##_BUCKET_CAPACITY;                                                 \
    v->size = 0;                                                                                   \
  }                                                                                                \
                                                                                                   \
  /** Cold path of @c _emplace: open the next bucket, reusing an already allocated one. */         \
  scope grd_result name##_grow(name *v, type **out_slot) {                                         \
    if (!v || !out_slot) return GRD_ERROR_NULL_POINTER;                                            \
    size_t next = v->tail ? v->tail_index + 1 : 0;                                                 \
    if (next >= v->bucket_count) {                                                                 \
      type *bucket;                                                                                \
      if (v->bucket_count == v->bucket_capacity) {                                                 \
        size_t new_capacity = v->bucket_capacity ? v->bucket_capacity * 2                          \
                                                 : (size_t)GRDU_BVEC_INDEX_INITIAL_CAPACITY;       \
        if (!grdu_bvec_index_grow(                                                                 \
                (void ***)&v->buckets, v->bucket_capacity, new_capacity, v->allocator              \
            )) {                                                                                   \
          return GRD_ERROR_OUT_OF_MEMORY;                                                          \
        }                                                                                          \
        v->bucket_capacity = new_capacity;                                                         \
      }                                                                                            \
      bucket = (type *)grdu_bvec_raw_alloc(                                                        \
          sizeof(type) * (size_t)name##_BUCKET_CAPACITY, v->allocator                              \
      );                                                                                           \
      if (!bucket) return GRD_ERROR_OUT_OF_MEMORY;                                                 \
      v->buckets[v->bucket_count++] = bucket;                                                      \
    }                                                                                              \
    v->tail = v->buckets[next];                                                                    \
    v->tail_index = next;                                                                          \
    v->tail_used = 1;                                                                              \
    v->size++;                                                                                     \
    *out_slot = v->tail;                                                                           \
    return GRD_SUCCESS;                                                                            \
  }                                                                                                \
                                                                                                   \
  /** Claim the next slot without writing it — construct large payloads in place. */               \
  scope grd_result name##_emplace(name *v, type **out_slot) {                                      \
    if (v->tail && v->tail_used < (size_t)name##_BUCKET_CAPACITY) {                                \
      *out_slot = v->tail + v->tail_used++;                                                        \
      v->size++;                                                                                   \
      return GRD_SUCCESS;                                                                          \
    }                                                                                              \
    return name##_grow(v, out_slot);                                                               \
  }                                                                                                \
                                                                                                   \
  /** Append a value. */                                                                           \
  scope grd_result name##_push(name *v, type value) {                                              \
    type *slot;                                                                                    \
    grd_result result = name##_emplace(v, &slot);                                                  \
    if (result != GRD_SUCCESS) return result;                                                      \
    *slot = value;                                                                                 \
    return GRD_SUCCESS;                                                                            \
  }                                                                                                \
                                                                                                   \
  /** Append a value read through a pointer — avoids passing bulky payloads by value.         */   \
  scope grd_result name##_push_ptr(name *v, const type *value) {                                   \
    type *slot;                                                                                    \
    grd_result result = name##_emplace(v, &slot);                                                  \
    if (result != GRD_SUCCESS) return result;                                                      \
    memcpy(slot, value, sizeof(type));                                                             \
    return GRD_SUCCESS;                                                                            \
  }                                                                                                \
                                                                                                   \
  /** Remove the last element. The vacated bucket stays allocated for the next push.     */        \
  scope grd_result name##_pop(name *v) {                                                           \
    if (!v->size) return GRD_ERROR_ARRAY_INDEX_OUT_OF_BOUNDS;                                      \
    v->size--;                                                                                     \
    if (--v->tail_used == 0) {                                                                     \
      if (v->size) {                                                                               \
        v->tail_index--;                                                                           \
        v->tail = v->buckets[v->tail_index];                                                       \
      } else {                                                                                     \
        v->tail = NULL;                                                                            \
        v->tail_index = 0;                                                                         \
      }                                                                                            \
      v->tail_used = (size_t)name##_BUCKET_CAPACITY;                                               \
    }                                                                                              \
    return GRD_SUCCESS;                                                                            \
  }                                                                                                \
                                                                                                   \
  /** Number of elements currently held. */                                                        \
  scope size_t name##_size(const name *v) {                                                        \
    return v->size;                                                                                \
  }                                                                                                \
                                                                                                   \
  /** Unchecked access — @p index must be < size. */                                               \
  scope type *name##_get(const name *v, size_t index) {                                            \
    return v->buckets[index >> (size_t)name##_BUCKET_SHIFT] +                                      \
           (index & (size_t)name##_BUCKET_MASK);                                                   \
  }                                                                                                \
                                                                                                   \
  /** Bounds-checked access; NULL when @p index has no element. */                                 \
  scope type *name##_at(const name *v, size_t index) {                                             \
    if (index >= v->size) return NULL;                                                             \
    return name##_get(v, index);                                                                   \
  }                                                                                                \
                                                                                                   \
  /** First element, or NULL while empty. */                                                       \
  scope type *name##_front(const name *v) {                                                        \
    return v->size ? v->buckets[0] : NULL;                                                         \
  }                                                                                                \
                                                                                                   \
  /** Last element, or NULL while empty. */                                                        \
  scope type *name##_back(const name *v) {                                                         \
    return v->tail ? v->tail + v->tail_used - 1 : NULL;                                            \
  }                                                                                                \
                                                                                                   \
  /** Number of buckets holding elements — the outer bound for bucket-wise iteration. */           \
  scope size_t name##_bucket_count(const name *v) {                                                \
    return v->tail ? v->tail_index + 1 : 0;                                                        \
  }                                                                                                \
                                                                                                   \
  /** Contiguous start of bucket @p bucket; @p bucket must be < _bucket_count(). */                \
  scope type *name##_bucket_data(const name *v, size_t bucket) {                                   \
    return v->buckets[bucket];                                                                     \
  }                                                                                                \
                                                                                                   \
  /** Elements held in bucket @p bucket; full except possibly the last one. */                     \
  scope size_t name##_bucket_size(const name *v, size_t bucket) {                                  \
    return bucket == v->tail_index ? v->tail_used : (size_t)name##_BUCKET_CAPACITY;                \
  }                                                                                                \
                                                                                                   \
  /** Flatten the sequence into one contiguous array, bucket by bucket. */                         \
  scope grd_result name##_copy_to(const name *v, type *dst, size_t dst_capacity) {                 \
    size_t bucket, buckets, written = 0;                                                           \
    if (!v || !dst) return GRD_ERROR_NULL_POINTER;                                                 \
    if (dst_capacity < v->size) return GRD_ERROR_DESTINATION_BUFFER_TO_SMALL;                      \
    buckets = name##_bucket_count(v);                                                              \
    for (bucket = 0; bucket < buckets; ++bucket) {                                                 \
      size_t count = name##_bucket_size(v, bucket);                                                \
      memcpy(dst + written, v->buckets[bucket], count * sizeof(type));                             \
      written += count;                                                                            \
    }                                                                                              \
    return GRD_SUCCESS;                                                                            \
  }

/**
 * @brief Generate a complete header-only container with internal linkage.
 *
 * Convenience shorthand for GRDU_BVEC_DECLARE() + GRDU_BVEC_DEFINE() with `static inline`
 * linkage. Every function inlines into its call site; unused ones are dropped by the compiler.
 *
 * @param name         Identifier of the generated type.
 * @param type         Payload type stored by value.
 * @param log2_bucket  Binary logarithm of the bucket size in elements (0 … 24).
 */
#define GRDU_BVEC_STATIC(name, type, log2_bucket)                                                  \
  GRDU_BVEC_DECLARE(name, type, log2_bucket, static inline)                                        \
  GRDU_BVEC_DEFINE(name, type, log2_bucket, static inline)

/**
 * @brief Walk every element in order.
 *
 * Assigns each element's address to @p item_ptr and exposes the running position as
 * @p index_var, a `size_t` declared by the macro. `break` and `continue` behave normally.
 *
 * @param name       Identifier of the generated type.
 * @param vec        Pointer to the vector.
 * @param item_ptr   Already declared `type *` receiving each element's address.
 * @param index_var  Name for the loop counter declared by this macro.
 *
 * @note For maximum throughput iterate bucket-wise instead, over contiguous memory:
 * @code
 * for (size_t b = 0, nb = tx_vec_bucket_count(&v); b < nb; ++b) {
 *   tx *data = tx_vec_bucket_data(&v, b);
 *   for (size_t i = 0, n = tx_vec_bucket_size(&v, b); i < n; ++i) { use(&data[i]); }
 * }
 * @endcode
 *
 * @whisper The sequence unrolls the way it was laid down
 */
#define GRDU_BVEC_FOREACH(name, vec, item_ptr, index_var)                                          \
  for (size_t index_var = 0;                                                                       \
       index_var < (vec)->size && (((item_ptr) = name##_get((vec), index_var)), 1); ++index_var)

/**
 * @}
 */

#ifdef __cplusplus
}
#endif

#endif // GRADIDO_BLOCKCHAIN_CORE_UTILS_BUCKET_VECTOR_H
